name: flutter_chatview_db_connection
description: "A new Flutter package project."
version: 0.0.1
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview_db_connection/issues
homepage: https://github.com/SimformSolutionsPvtLtd/flutter_chatview_db_connection

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7

  flutter:
    sdk: flutter

  # TODO(YASH): Use pub.dev version once this repo is published.
  flutter_chatview_models:
    git:
      url: https://github.com/SimformSolutionsPvtLtd/flutter_chatview_models

  http: ^1.3.0
  intl: ^0.20.0
  path: ^1.9.0
  rxdart: ^0.28.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
