name: chatview_db_connection
description: "Specialized wrapper for chatview package providing seamless integration with Database & Storage for your flutter chat app."
version: 0.0.1
issue_tracker: https://github.com/SimformSolutionsPvtLtd/chatview_db_connection/issues
homepage: https://github.com/SimformSolutionsPvtLtd/chatview_db_connection
topics:
  - chat
  - chatview
  - firebase
  - plug and play
  - backend integration
  - chat backend

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7

  flutter:
    sdk: flutter

  # TODO(YASH): Use pub.dev version once this repo is published.
  chatview_models:
    git:
      url: https://github.com/SimformSolutionsPvtLtd/chatview_models

  http: ^1.3.0
  intl: ^0.20.0
  path: ^1.9.0
  rxdart: ^0.28.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
