name: flutter_chatview_db_connection
description: "A new Flutter package project."
version: 0.0.1
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview_db_connection/issues
homepage: https://github.com/SimformSolutionsPvtLtd/flutter_chatview_db_connection

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0
  path: ^1.9.0
  intl: ^0.20.0
  # TODO(YASH): Remove this once centralised repository is created for using same models and enums
  chatview: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
