// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9vwFUaJX_CudiGttYGl0CuE-twx3q_Cw',
    appId: '1:148312244410:web:297d64801a3344035e8283',
    messagingSenderId: '148312244410',
    projectId: 'chat-view-demo',
    authDomain: 'chat-view-demo.firebaseapp.com',
    storageBucket: 'chat-view-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADSpO_SpCiB5Ss02_3-ksQkTal-UV3-5I',
    appId: '1:148312244410:android:2e011be695c236b15e8283',
    messagingSenderId: '148312244410',
    projectId: 'chat-view-demo',
    storageBucket: 'chat-view-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOjGFBrpiK-WpDCHnv1y32Dib0ZcauYFQ',
    appId: '1:148312244410:ios:f415421a8cfa006a5e8283',
    messagingSenderId: '148312244410',
    projectId: 'chat-view-demo',
    storageBucket: 'chat-view-demo.appspot.com',
    iosBundleId: 'com.simform.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOjGFBrpiK-WpDCHnv1y32Dib0ZcauYFQ',
    appId: '1:148312244410:ios:f415421a8cfa006a5e8283',
    messagingSenderId: '148312244410',
    projectId: 'chat-view-demo',
    storageBucket: 'chat-view-demo.appspot.com',
    iosBundleId: 'com.simform.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9vwFUaJX_CudiGttYGl0CuE-twx3q_Cw',
    appId: '1:148312244410:web:0344d81afe204b685e8283',
    messagingSenderId: '148312244410',
    projectId: 'chat-view-demo',
    authDomain: 'chat-view-demo.firebaseapp.com',
    storageBucket: 'chat-view-demo.appspot.com',
  );
}
